task_logger_task_logger:
    resource: "@TaskLoggerTaskLoggerBundle/Controller"
    type: annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"