security:
    encoders:
      FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        assets:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            anonymous: ~
        main:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout: true
            anonymous: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/jira, roles: ROLE_JIRA_USER }

    role_hierarchy:
        ROLE_JIRA_USER: ROLE_USER
        ROLE_ADMIN: ROLE_USER