services:
    jira_api:
        class: Haniki\TaskLoggerBundle\Services\JiraApi
        arguments: ["@security.context"]
    task_logger_user.profile.form.type:
        class: Haniki\TaskLoggerBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: task_logger_user_profile }