services:
    jira_basic:
        class: chobie\Jira\Api\Authentication\Basic
        arguments: [%jira_username%, %jira_password%]
    jira_api:
        class: chobie\Jira\Api
        arguments: [%jira_url%, "@jira_basic"]
