<?php

namespace TaskLogger\TaskLoggerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WorkLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkLogRepository extends EntityRepository
{
}
